### ISSUE TITLE
希望增加字体粗细调整和对齐方式

### ISSUE THREAD

**Issue by 22Frederic** [mo-jinran/Taskbar-Lyrics#10]
效果如下图，增加增加文字粗细易于调整，而个人更喜欢以整个任务栏居中，现在好像只有以任务栏空白部分居中（也可能是我没找到？）

谢谢作者大大！

![屏幕截图_20230123_150633](https://user-images.githubusercontent.com/105597335/213983907-35223fa2-6cef-4e4e-bb5a-01d66aa4ec84.png)

**Comment by mo-jinran** [comment]
![image](https://user-images.githubusercontent.com/66980784/218101677-ace76549-d09f-4efc-b36d-c368e42769d0.png)
目前只能这个样子，应该足够了（其实是我比较笨菜（（

**Comment by mo-jinran** [comment]
基于整个任务栏的居中正在做了，下个版本就能使用

**Comment by 22Frederic** [comment]
谢谢大佬，效果很好！还有，希望能自定义限制歌词显示长度，过长的歌词滚动播放，这样不容易与图标重叠

**Comment by mo-jinran** [comment]
![image](https://user-images.githubusercontent.com/66980784/218381326-67c40b50-e644-4c49-9c4c-abe78ba15c3b.png)
![image](https://user-images.githubusercontent.com/66980784/218381463-0bbda5ce-c687-4a5e-a9ed-0068827bff8b.png)
基于整个任务栏宽度居中的歌词，会根据剩余空间调整自身大小位置

**Comment by mo-jinran** [comment]
![image](https://user-images.githubusercontent.com/66980784/220278379-2104ef6e-0e63-41a3-bc4e-1bbef56a399c.png)
把字体粗细调节加回去了，并且从细到粗调节

**Comment by mo-jinran** [comment]
![image](https://user-images.githubusercontent.com/66980784/220349256-4402dfdf-4c9d-47b5-9d43-0553021a585b.png)
优化了一下，已推送代码，等待插件商店爬取，留意1.4.2更新

**Comment by 22Frederic** [comment]
谢谢，再次感谢大佬的辛勤付出！
