### ISSUE TITLE
这个是怎么更换字体的，字体的选取范围是根据什么定的。额外安装的字体可以使用吗。

### ISSUE THREAD

**Issue by xuanwohanser** [mo-jinran/Taskbar-Lyrics#11]

**Comment by mo-jinran** [comment]
[https://github.com/mo-jinran/Taskbar-Lyrics/issues/12#issuecomment-1404750924](url)

**Comment by mo-jinran** [comment]
https://github.com/mo-jinran/Taskbar-Lyrics/issues/12#issuecomment-1404750924
