### ISSUE TITLE
进度条拖动之后歌词不能同步 并且字体会有显示不全的问题

### ISSUE THREAD

**Issue by NODT4109** [mo-jinran/Taskbar-Lyrics#12]
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/109859658/214563820-eca6dc89-6abf-49a2-99a4-5fa794eed055.png">
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/109859658/214564070-59a20ca1-41d4-47da-86ae-dea501c363c1.png">
如图1 测试过很多歌曲都是拖动进度条之后歌词没办法同步 图二的问题就是作曲人信息太多的情况下信息显示不全 上下会被挡住一部分 这个问题是大概率发生的 有时候会正常显示（备注：更换过字体 字体是Minecraft AE 是后期安装的 字体在压缩包里）
[[苦力怕论坛]Minecraft(同时支持中英文).zip](https://github.com/mo-jinran/Taskbar-Lyrics/files/10499285/Minecraft.zip)

**Comment by xuanwohanser** [comment]
后期安装的字体怎么更换啊，我安装的字体无法使用

**Comment by NODT4109** [comment]
要先知道字体叫什么 可以去字体文件夹里面找自己安装的字体 点击字体会跳出来这样的弹窗 以我的Minecraft AE字体举个例子，左上角的字体名称就是字体的名字（字体文件夹在C:\Windows\Fonts这个目录下面）
<img width="801" alt="image" src="https://user-images.githubusercontent.com/109859658/214801312-8d09eb2f-a543-4d31-b006-e89c961eb6fa.png">
其次就是把字体名字输入到taskbar lyrics的更换字体一栏去 比如我的字体的名字就是Minecraft AE 直接复制粘贴丢进去（不要打错），点击应用，此时大概率任务栏是不会有歌词的，这个时候就要重启网易云，不行就多试几次，或者重启网易云后用可以使用的字体和安装的字体来回切换几次试试，基本上就可以使用了。如果上述方法还是不行就重启电脑，总能成功的
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/109859658/214803012-a931378b-079a-469f-be0b-075f294c94c9.png">

**Comment by mo-jinran** [comment]
不要着急，新年休假，初八开始修

**Comment by mo-jinran** [comment]
图一的问题我貌似无法复现

**Comment by mo-jinran** [comment]
图二修好了，但是还没做滚动歌词

**Comment by NODT4109** [comment]
> 

啊 明白了 等能正常使用插件的时候我再去看看
