### ISSUE TITLE
”一起听“状态下无法显示

### ISSUE THREAD

**Issue by HermosMerlin** [mo-jinran/Taskbar-Lyrics#14]
如题，在”一起听“状态下无法显示歌词。

**Comment by HermosMerlin** [comment]
更新，在退出”一起听“后，插件将从列表中消失，并且在插件商店内 下载—重载 的常规流程无法回复，但是taskbar lycris.exe的进程并未中断。
在结束进程后，清理插件文件夹内所有此插件残留，即可正常重新下载。
并未多次测试，无法确定能否稳定触发。

**Comment by mo-jinran** [comment]
无法复现，并且我这里一直都是在一起听
可以尝试更新到最新版试试看
