### ISSUE TITLE
与LibFrontendPlay不兼容

### ISSUE THREAD

**Issue by HermosMerlin** [mo-jinran/Taskbar-Lyrics#15]
如题，在安装LibFrontendPlay插件后TaskbarLyrics会消失，解决方法是删除LibFrontendPlay后结束Taskbarlyrics进程，并重新安装。
重点在于触发类似bug时，任务栏歌词基本处于停滞状态，即持续显示上一句歌词，即使关闭网易云。
建议添加对于自身状态或者网易云状态的检测

**Comment by mo-jinran** [comment]
不会兼容LibFrontendPlay，但是以后会更改歌词获取方式来解决此问题
对于网易云状态检测，其实一直都是有的，现在已经更加完善一些了

**Comment by mo-jinran** [comment]
不过我这里LibFrontendPlay是可以正常使用兼容任务栏歌词的，无法复现
