### ISSUE TITLE
1.2版本会导致网易云无法打开，把插件删了就又能打开了

### ISSUE THREAD

**Issue by Demisse233** [mo-jinran/Taskbar-Lyrics#17]

**Comment by mo-jinran** [comment]
正在修，昨天晚上手残把3MB大小的pdb文件上传了，然而Gitee只能直连下不超过1MB大小文件，导致插件下载后Gitee返回错误的html页面而非压缩包，BetterNCM解压失败导致无法打开

**Comment by mo-jinran** [comment]
等待插件仓库刷新，插件更新到1.2.2版本（1.2.1版本是Debug版传错了
