### ISSUE TITLE
更新1.2版本之后网易云出现打不开状况

### ISSUE THREAD

**Issue by NODT4109** [mo-jinran/Taskbar-Lyrics#19]
如题，已经尝试过重新安装网易云和betterNCM插件但是无效果，排查认为是更新之后的插件问题，删除任务栏歌词插件之后可以正常进入网易云，windows11版本为22H2

**Comment by mo-jinran** [comment]
等待插件仓库刷新，插件更新到1.2.2版本（1.2.1版本是Debug版传错了
