### ISSUE TITLE
希望能增加修改字体的功能

### ISSUE THREAD

**Issue by CamusY** [mo-jinran/Taskbar-Lyrics#2]
希望能在设置中增加修改字体的功能，或通过配置文件修改字体，感谢！

**Comment by mo-jinran** [comment]
![image](https://user-images.githubusercontent.com/66980784/212712842-4aa586a1-2b87-44ac-9ba6-a2aee0a68959.png)

**Comment by mo-jinran** [comment]
已完成

**Comment by CamusY** [comment]
感谢！
