### ISSUE TITLE
1.2.1版本会弹出终端，显示歌词也会有白框

### ISSUE THREAD

**Issue by Yeah-le** [mo-jinran/Taskbar-Lyrics#20]
![Snipaste_2023-01-31_15-32-06](https://user-images.githubusercontent.com/76760776/215696075-4a7beb61-d6d7-45e4-9523-b19b3b9f8eca.png)
系统版本为22h2，希望可以和之前版本一样

**Comment by mo-jinran** [comment]
等待插件仓库刷新，插件更新到1.2.2版本（1.2.1版本是Debug版传错了
