### ISSUE TITLE
作者大大，建议可以把运行时程序窗口隐藏

### ISSUE THREAD

**Issue by 2055135** [mo-jinran/Taskbar-Lyrics#21]
![image](https://user-images.githubusercontent.com/119772101/215708819-14623ba9-3960-43f7-b526-9d27c4d5694b.png)

**Comment by 2055135** [comment]
插件更新后出现的这个问题

**Comment by mo-jinran** [comment]
1.2.1版本是上传了错误的Debug版本，等待插件商店内更新到1.2.2即可
