### ISSUE TITLE
安装了插件状态栏不显示歌词

### ISSUE THREAD

**Issue by mikasalzx** [mo-jinran/Taskbar-Lyrics#22]
请问怎么使用呢，安装了1.2.2版本的插件，但是状态栏不显示，点了歌词还是显示在桌面

**Comment by mo-jinran** [comment]
需要Windows 11 22H2版本与21H2（22H2 22623以上不可用）

**Comment by mikasalzx** [comment]
好的谢谢，我正好是22623.1245

**Comment by mo-jinran** [comment]
问题已修复：https://github.com/mo-jinran/Taskbar-Lyrics/issues/3#issuecomment-1418958045
