### ISSUE TITLE
在屏幕左下角显示两行歌词时与屏幕边缘距离过近，希望可以出调节边距功能

### ISSUE THREAD

**Issue by JTFA** [mo-jinran/Taskbar-Lyrics#23]

**Comment by mo-jinran** [comment]
![CTFO0LXGH50BRCT$ ZI%Z)8](https://user-images.githubusercontent.com/66980784/218018848-b22e3bf8-9b84-4844-9144-46030bd73614.png)
自定义边距，目前只能左右
