### ISSUE TITLE
任务栏歌词有时会导致网易云音乐无法打开

### ISSUE THREAD

**Issue by XueGaoawa** [mo-jinran/Taskbar-Lyrics#25]
![image](https://user-images.githubusercontent.com/124153584/216029687-468aad93-ba54-43df-8153-6c330bc2aa35.png)
在22621.1105上，我用BetterNCM装了个任务栏歌词v1.2.2，然后就发现无法用双击等方式打开网易云了（
把所有的模块卸载了就剩个任务栏歌词也会无法打开网易云

**Comment by XueGaoawa** [comment]
但是我把任务栏歌词v1.2.2的文件拖出betterncm的plugin文件夹之后，把其他的插件再加回去（或者不加插件，就一个pluginmarket），网易云就可以正常打开了

**Comment by HandsomeYDZ** [comment]
我的任务栏歌词文件在plugin文件夹里甚至是乱码，然后如果不重启网易云，直接装了插件之后，甚至会弹出一个命令行窗口，然后任务栏里会出现两个框框（重启后直接打不开了）。不知道怎么回事反正，就是插件有问题，望修复。而且是最新版有问题，之前是没问题的，升级后就寄了，希望能康康是哪里出问题了，改回去？

**Comment by mo-jinran** [comment]
> 我的任务栏歌词文件在plugin文件夹里甚至是乱码，然后如果不重启网易云，直接装了插件之后，甚至会弹出一个命令行窗口，然后任务栏里会出现两个框框（重启后直接打不开了）。不知道怎么回事反正，就是插件有问题，望修复。而且是最新版有问题，之前是没问题的，升级后就寄了，希望能康康是哪里出问题了，改回去？

这是用的1.2.1版本才会会弹出命令行窗口（因为上传了错误的Debug版本。安装1.2.2即可

**Comment by XueGaoawa** [comment]
我在更新了BetterNCM之后，这个问题不存在了

**Comment by HandsomeYDZ** [comment]
谢谢，知道了，感谢大佬

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年2月1日 21:40
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [mo-jinran/Taskbar-Lyrics] 任务栏歌词有时会导致网易云音乐无法打开 (Issue #25)


我的任务栏歌词文件在plugin文件夹里甚至是乱码，然后如果不重启网易云，直接装了插件之后，甚至会弹出一个命令行窗口，然后任务栏里会出现两个框框（重启后直接打不开了）。不知道怎么回事反正，就是插件有问题，望修复。而且是最新版有问题，之前是没问题的，升级后就寄了，希望能康康是哪里出问题了，改回去？

这是用的1.2.1版本才会会弹出命令行窗口（因为上传了错误的Debug版本。安装1.2.2即可

―
