### ISSUE TITLE
任务栏歌词有些时候会挡住任务栏的一部分图标

### ISSUE THREAD

**Issue by FR0Z3** [mo-jinran/Taskbar-Lyrics#26]
这个问题貌似只会出现在窗口位置设置为右且父任务栏为主屏幕的时候出现。且切换窗口之后会导致任务栏歌词跑到副屏幕（？）去，需要手动调回来。我这边有在用Start11，任务栏对齐方式为左对齐，这目前也是我改不了居中对齐的原因...?
Edit: 我这边的笔电是没有副屏的，导致任务栏歌词失去焦点的这个问题似乎于 #24 一致。 
BetterNCM 版本：1.0（非测试通道）
Taskbar-Lyrics 版本：1.2.2
网易云客户端版本：2.10.6 Build 2000601（Patch 1:5ad43a6）
Win11版本号：22H2 Build 22621.1105

![tskbar_Scrshot01](https://user-images.githubusercontent.com/33184021/216189299-6afbb130-9157-4e76-b9fc-eb8138b3ddcb.jpg)
![tskbar_Scrshot02](https://user-images.githubusercontent.com/33184021/216189309-cec03a89-57c4-4dc6-9604-ce5079904293.jpg)

**Comment by mo-jinran** [comment]
更新到最新版本后这个问题是否有解决？

**Comment by FR0Z3** [comment]
> 更新到最新版本后这个问题是否有解决？

遮挡问题有解决。但是任务栏如果有新程序打开/关闭会导致歌词消失，当然切换窗口甚至点击任务栏隐藏图标的那一栏也会导致这样，重新开关一下歌词有时候会导致无法获取歌词。

**Comment by FR0Z3** [comment]
https://user-images.githubusercontent.com/33184021/217789978-be8cbd8b-2e84-4c07-ac06-0f474036f202.mp4

用于参考上面问题的录像。

**Comment by mo-jinran** [comment]
那应该是Start11的问题了，以后可能会去解决

**Comment by mo-jinran** [comment]
![image](https://user-images.githubusercontent.com/66980784/218381768-46ba7e3c-484e-4883-9f7d-b41b7dac7598.png)
可以先用修改边距功能
