### ISSUE TITLE
与其他显示在任务栏的应用冲突

### ISSUE THREAD

**Issue by RingZc** [mo-jinran/Taskbar-Lyrics#28]
win11 22H2 
在任务栏居左时，与TrafficMonitor的性能显示冲突

**Comment by PIut02** [comment]
1.2.3版本会与TrafficMonitor的显示重叠，希望保持原来直接覆盖上层的显示方式

**Comment by wangzipai** [comment]
最新版本与TrafficMonitor重叠，之前的不会

**Comment by mo-jinran** [comment]
TrafficMonitor我自己也在用，是个已知问题，会修的不要着急

**Comment by mo-jinran** [comment]
想了想，感觉不是很好做。之前的窗口是不透明的只是放在任务栏上莫名其妙透明了所以能覆盖掉TrafficMonitor，现在窗口是真的透明了所以覆盖不掉TrafficMonitor。目前我的想法是把TrafficMonitor隐藏，或者留出一块空地给TrafficMonitor显示（自定义左右边距距离，而且还能解决其他这类软件的问题

**Comment by mo-jinran** [comment]
![CTFO0LXGH50BRCT$ ZI%Z)8](https://user-images.githubusercontent.com/66980784/218018454-f344fb7e-7cd5-4021-8b77-eabf101aab7b.png)
自定义调节左右边距，支持负数
