### ISSUE TITLE
beta预览版win11无法使用状态栏歌词

### ISSUE THREAD

**Issue by 15Shell** [mo-jinran/Taskbar-Lyrics#3]
如图所示
![image](https://user-images.githubusercontent.com/111548938/212682872-163c50c1-6d9c-4d57-a9f5-b65d41fdc764.png)
![image](https://user-images.githubusercontent.com/111548938/212683069-d01ab1c2-7d0e-45e2-914e-7442bf4a951d.png)

**Comment by zhuzixuan2019241** [comment]
同上，我是Dev版
![image](https://user-images.githubusercontent.com/68471692/212788140-2a6a1f26-cff9-41ca-a39d-e94642fea9d9.png)
ca猜测与内部版本默认开启为平板电脑增强的任务栏导致此问题，详见https://github.com/TranslucentTB/TranslucentTB/issues/537（我并未对此猜想做过验证

**Comment by zhuzixuan2019241** [comment]
> 同上，我是Dev版 ![image](https://user-images.githubusercontent.com/68471692/212788140-2a6a1f26-cff9-41ca-a39d-e94642fea9d9.png) 猜测与内部版本默认开启为平板电脑增强的任务栏导致此问题，详见[TranslucentTB/TranslucentTB#537](https://github.com/TranslucentTB/TranslucentTB/issues/537) （我并未对此猜想做过验证

![image](https://user-images.githubusercontent.com/68471692/212789141-ff2ac9dc-3506-440e-8d1d-65f36ec045a2.png)
![image](https://user-images.githubusercontent.com/68471692/212789037-b1b7c738-38d6-4fc6-845e-6fcb9d8ab81c.png)
https://blogs.windows.com/windows-insider/2022/09/29/announcing-windows-11-insider-preview-build-22621-730-and-22623-730/

**Comment by mo-jinran** [comment]
优先解决Windows Release版下的问题&功能，Beta版及Dev版不会优先修复。等我修完其他问题后再来解决此问题

**Comment by mo-jinran** [comment]
目前判定的原因为新版任务栏下类名为“Windows.UI.Composition.DesktopWindowContentBridge”的窗口将任务栏歌词覆盖，导致歌词显示在下方

**Comment by zhuzixuan2019241** [comment]
> 优先解决Windows Release版下的问题&功能，Beta版及Dev版不会优先修复。等我修完其他问题后再来解决此问题

ok谢谢

**Comment by 15Shell** [comment]
> 优先解决Windows Release版下的问题&功能，Beta版及Dev版不会优先修复。等我修完其他问题后再来解决此问题

好的，那就耐心等待了

**Comment by kaliCYH** [comment]
用vivetool工具输入：vivetool /disable /id:26008830 禁用后正常显示，Windows 11 22h2 22623.1037

**Comment by 0x00A0** [comment]
> 

实测在22H2 22623.1180上有效，thx！

**Comment by zhuzixuan2019241** [comment]
我之前发的TranslucentTB的issue里有，这一方法在Beta和旧版Dev上确实有效，但仅针对Dev25261之前的版本，更新的版本每次重启就会自动恢复新版任务栏

**Comment by Suichen-QwQ** [comment]
> 用vivetool工具输入：vivetool /disable /id:26008830 禁用后正常显示，Windows 11 22h2 22623.1037

谢谢，最新预览版win11修改后桌面黑屏，无法重新再开启这个功能，谢谢让我决定回到win11正式版

**Comment by ProphetCai** [comment]
> > 用vivetool工具输入：vivetool /disable /id:26008830 禁用后正常显示，Windows 11 22h2 22623.1037
> 
> 谢谢，最新预览版win11修改后桌面黑屏，无法重新再开启这个功能，谢谢让我决定回到win11正式版

哈哈哈哈哈哈

**Comment by mo-jinran** [comment]
这个问题已修复（应该可以支持所有Win11的任务栏或者第三方软件？），等待我再修点bug发新版本

**Comment by kaliCYH** [comment]
> > 用vivetool工具输入：vivetool /disable /id:26008830 禁用后正常显示，Windows 11 22h2 22623.1037
> 
> 谢谢，最新预览版win11修改后桌面黑屏，无法重新再开启这个功能，谢谢让我决定回到win11正式版

谢谢告知，我昨天从beta切换到dev更新到最新内测就发现应该是这个的问题，又用vivetool /enable /id:26008830恢复回去了

**Comment by kaliCYH** [comment]
> 这个问题已修复（应该可以支持所有Win11的任务栏或者第三方软件？），等待我再修点bug发新版本

Windows 11 专业工作站版 22h2 25295.1000没问题

**Comment by RERASER** [comment]
![image](https://user-images.githubusercontent.com/63722060/229308512-4b42d881-11e4-49eb-ae4c-984123f3b7b9.png)
![image](https://user-images.githubusercontent.com/63722060/229308511-d29f675c-01ea-4c8a-9029-544e30526d17.png)
还是不显示歌词(开启旧版任务栏会导致黑屏 在相关更新后旧版任务栏代码已被移除)
