### ISSUE TITLE
希望开关功能可以与软件自带设置里的启用歌词选项同步

### ISSUE THREAD

**Issue by JTFA** [mo-jinran/Taskbar-Lyrics#34]
就是用播放按钮右边那个“词”按钮控制开启与关闭，不知道好不好实现，如果实现不了就当我没说hhh

**Comment by mo-jinran** [comment]
但是那是桌面歌词的开关（
会导致全都打开/关闭

**Comment by JTFA** [comment]
> 但是那是桌面歌词的开关（ 会导致全都打开/关闭

或许可以给个开关决定是否同步？比如我可以把软件自带的歌词设置为“软件内词栏”，再用其他插件拿css把软件内词栏屏蔽掉（（

**Comment by mo-jinran** [comment]
草那还不如直接用插件内的开关，也就只需要多点两下而已不麻烦

> > 但是那是桌面歌词的开关（ 会导致全都打开/关闭
> 
> 或许可以给个开关决定是否同步？比如我可以把软件自带的歌词设置为“软件内词栏”，再用其他插件拿css把软件内词栏屏蔽掉（（

**Comment by mo-jinran** [comment]
而且这种低频率使用的功能，谁会闲着没事开关那玩意（而且本来就是为了在任务栏上显示，干嘛关掉（

**Comment by JTFA** [comment]
> 而且这种低频率使用的功能，谁会闲着没事开关那玩意（而且本来就是为了在任务栏上显示，干嘛关掉（

哈哈哈好像有道理 我是之前用自带的习惯随时开关了（
