### ISSUE TITLE
betterncm怎么了，插件市场和官网都没了

### ISSUE THREAD

**Issue by ChaserLaNcE** [mo-jinran/Taskbar-Lyrics#36]

**Comment by mo-jinran** [comment]
因为隔壁的MC搞事情，怕搞到这边所以暂时跑路了（

**Comment by ChaserLaNcE** [comment]
草，原来是这样，我最近也是看到了这个事情，网易吃相难看😓


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月17日(周五) 晚上8:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [mo-jinran/Taskbar-Lyrics] betterncm怎么了，插件市场和官网都没了 (Issue #36)




 
因为隔壁的MC搞事情，怕搞到这边所以暂时跑路了（
 
&mdash;
