### ISSUE TITLE
一些恳求🥺

### ISSUE THREAD

**Issue by nuyaot** [mo-jinran/Taskbar-Lyrics#39]
今天更新之后发现原本对齐方式里面的斜体没有了，个人特别喜欢这个🥺，希望作者大大可以在下次更新的时候重新添加回来，十分感谢！🥺

**Comment by nuyaot** [comment]
回看了一下具体是字体样式的那个又粗又斜，真的希望能回滚一下🥺

**Comment by mo-jinran** [comment]
![image](https://user-images.githubusercontent.com/66980784/220278579-9312a8db-9d12-4eb8-a944-2b2e243d376c.png)
加回去了，现在可以单独设置每一项

**Comment by mo-jinran** [comment]
![image](https://user-images.githubusercontent.com/66980784/220348776-8262555d-9df2-4157-a8a3-5a4e2c26b778.png)
优化了一下，已推送代码，等待插件商店爬取，留意1.4.2更新
