### ISSUE TITLE
希望能增加修改位置的功能，感谢！

### ISSUE THREAD

**Issue by LongC-CN** [mo-jinran/Taskbar-Lyrics#4]
![image](https://user-images.githubusercontent.com/61483728/212827131-0e3d42a3-b495-4c10-b716-c3c6844ed3c0.png)
希望增加调整水平位置的功能
对齐方式是靠左时会被挡住
可以把他调整到托盘图标左边

**Comment by LongC-CN** [comment]
可以的话希望支持一下StartAllBack
![image](https://user-images.githubusercontent.com/61483728/212828010-2eb6f9a2-bd29-4022-b3e4-c6fa4ee9d6ea.png)

**Comment by LongC-CN** [comment]
打开网易云后重启资源管理器，再重启网易云会闪退并出现单独的taskbar-lyrics.exe进程，需要手动关闭才能打开网易云
希望这个也优化一下

**Comment by mo-jinran** [comment]
> ![image](https://user-images.githubusercontent.com/61483728/212827131-0e3d42a3-b495-4c10-b716-c3c6844ed3c0.png) 希望增加调整水平位置的功能 对齐方式是靠左时会被挡住 可以把他调整到托盘图标左边

![image](https://user-images.githubusercontent.com/66980784/213639052-ef03c259-ef68-4d8f-99ee-057034e6f9e3.png)
