### ISSUE TITLE
歌词居右时最后一个字只显示一半

### ISSUE THREAD

**Issue by Torther** [mo-jinran/Taskbar-Lyrics#41]
如图
![image](https://user-images.githubusercontent.com/29655416/220921149-63a83081-822e-46e0-9e7a-bcdf88d61db7.png)
居左和居中时正常
版本1.4.2

**Comment by mxlt02** [comment]
![image](https://user-images.githubusercontent.com/57489136/221398349-d6ce4384-12e2-44b1-816f-0a680c62ed04.png)
same

**Comment by mo-jinran** [comment]
已修复，等待我发布1.5.4版本
