### ISSUE TITLE
有一部分勾选框的状态没有保存下来 ，关闭软件后下次打开，之前的选项都没了

### ISSUE THREAD

**Issue by LKZD7** [mo-jinran/Taskbar-Lyrics#42]
![QQ截图20230225002444](https://user-images.githubusercontent.com/33388137/221232730-39e4669f-a5d7-46af-b567-649b18cbe3d8.png)

![QQ截图20230225002520](https://user-images.githubusercontent.com/33388137/221232753-3198bd8c-243d-4878-8a1b-554e1fcc15e4.png)

比如，我把歌词开关的勾去掉了，下次打开还在。
图中红框里的选项都有类似问题。

**Comment by mo-jinran** [comment]
网易云音乐版本是2.10.7吗？如果是，这是软件自身问题

**Comment by LKZD7** [comment]
![image](https://user-images.githubusercontent.com/33388137/221359479-a835bb79-18fb-4b0a-9ab6-ceea1a78f9bd.png)
好的，谢谢
