### ISSUE TITLE
版本更新之后更改字体无法使用

### ISSUE THREAD

**Issue by NODT4109** [mo-jinran/Taskbar-Lyrics#43]
如题 今天更新之后字体变成了雅黑 但是我的字体是Minecraft AE 多次点击应用没有反应
版本	Windows 11 家庭中文版
版本	22H2
安装日期	‎2022/‎12/‎19
操作系统版本	22621.1265
体验	Windows Feature Experience Pack 1000.22638.1000.0
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/109859658/221390454-6cc3928d-c87d-46c9-90c3-7b3b4da44933.png">

**Comment by mo-jinran** [comment]
字体名不是Minecraft AE，请使用Minecraft AE Pixel
