### ISSUE TITLE
开启该插件会导致系统睡眠再唤醒之后屏幕出现小黑块

### ISSUE THREAD

**Issue by JTFA** [mo-jinran/Taskbar-Lyrics#46]
在开启插件的情况下，电脑睡眠再唤醒之后鼠标经过的地方会经常出现像图上这样的小黑块，然后鼠标再划过黑块之后黑块就消失了。在文件资源管理器界面快速动几下鼠标就能复现，关掉网易云或直接任务管理器结束taskbar-lyrics.exe任务之后就不会再出现了，所以应该是这个插件导致的吧...
<img width="69" alt="c00ccbfc974d8014f50fb2cbcc3250e" src="https://user-images.githubusercontent.com/57850248/222904122-9d589f51-5feb-42ef-8ab2-0319e70e5775.png">
<img width="164" alt="451649002e6e1027c3e652cbcba5a52" src="https://user-images.githubusercontent.com/57850248/222904127-77b5defc-4492-4e8f-ae27-1de0d3530c5b.png">
不知道是我电脑的问题还是普遍现象...

**Comment by mo-jinran** [comment]
无法复现
