### ISSUE TITLE
字体更换失效

### ISSUE THREAD

**Issue by omoidesu** [mo-jinran/Taskbar-Lyrics#47]
插件版本：1.4.3
系统版本：Windows 11 专业版 Insider Preview 25309.1000

之前更换了得意黑，任务栏上字体是可以正常使用的。今天唤醒电脑后字体显示变成了微软雅黑，但设置中依然是之前的得意黑

**Comment by omoidesu** [comment]
尝试了更换其他字体，系统预装的字体都可以正常更换，自己后安装的字体在任务栏上都有问题

**Comment by mo-jinran** [comment]
无法复现，正常使用

**Comment by omoidesu** [comment]
今天重启电脑后突然正常了，怀疑是系统问题
可以close了
