### ISSUE TITLE
启动时出现未知错误，导致整个插件出现崩溃

### ISSUE THREAD

**Issue by 2055135** [mo-jinran/Taskbar-Lyrics#48]
启动时出现未知错误，导致整个插件出现崩溃，已尝试切换为实验版本，错误依旧
![image](https://user-images.githubusercontent.com/119772101/224495738-1476c33e-1fc7-4ffb-84da-16b415191b06.png)

**Comment by 2055135** [comment]
补充一下额外信息
Windows系统版本：版本	Windows 11 家庭中文版
版本	22H2
安装日期	‎2022/‎11/‎12
操作系统版本	22621.1344
体验	Windows Feature Experience Pack 1000.22639.1000.0
网易云版本：2.10.7

**Comment by Keith-the-wise** [comment]
<img width="262" alt="uTools_1678688298279" src="https://user-images.githubusercontent.com/77421813/224622890-2427c517-7b06-4784-9b77-5e30a8079b82.png">

**Comment by Keith-the-wise** [comment]
> <img alt="uTools_1678688298279" width="262" src="https://user-images.githubusercontent.com/77421813/224622890-2427c517-7b06-4784-9b77-5e30a8079b82.png">

跟楼主一样，应该是更新了BetterNcm1.1.0后出的问题

**Comment by Keith-the-wise** [comment]
不知道因为什么情况，不能播放本地音乐了，关掉了任务栏歌词插件也不不行，只能播放网络歌曲

**Comment by Nervedao** [comment]
更新完BNCM1.1.0后，斜体下划线之类的无了，而且歌词跑到上方了
![图片](https://user-images.githubusercontent.com/127742402/224679574-924bafd7-490c-405a-8b3f-ba3f79a34445.png)
![Uploading 图片.png…]()
