### ISSUE TITLE
NCM任务栏歌词bug反馈

### ISSUE THREAD

**Issue by 24Piggie** [mo-jinran/Taskbar-Lyrics#49]
右对齐的时候会出现最右边的字缩进去半个，挺久的bug了   之前是不会的

![任务栏歌词bug反馈](https://user-images.githubusercontent.com/83473608/224714642-c8430e42-ec99-4d90-9034-6dafa460dc17.png)

**Comment by mo-jinran** [comment]
已修复，等待我发布1.5.4版本

**Comment by 24Piggie** [comment]
OK的，辛苦作者啦！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月18日(周六) 晚上8:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [mo-jinran/Taskbar-Lyrics] NCM任务栏歌词bug反馈 (Issue #49)




 
已修复，等待我发布1.5.4版本
