### ISSUE TITLE
歌词溢出

### ISSUE THREAD

**Issue by LJY7812** [mo-jinran/Taskbar-Lyrics#5]
![image](https://user-images.githubusercontent.com/103030400/212835367-c5eae748-dd93-495e-8e1e-c78fcf2e8018.png)

如图，歌词溢出，可以添加歌词移动或者直接显示后半段歌词

**Comment by mo-jinran** [comment]
使用1.0.4解决被图标覆盖问题，但是字体超出滚动目前不太好做
