### ISSUE TITLE
新版 字体样式bug

### ISSUE THREAD

**Issue by fishdown** [mo-jinran/Taskbar-Lyrics#51]
![屏幕截图 2023-03-14 192823](https://user-images.githubusercontent.com/119657362/224987389-cd1a4cdb-da90-4d42-a0c4-545857019c85.png)

点起来不起作用

**Comment by mo-jinran** [comment]
按F12切换到Console查看报错日志

**Comment by fishdown** [comment]
![屏幕截图 2023-03-14 194046](https://user-images.githubusercontent.com/119657362/224990564-d859eaf7-cccf-4773-9856-20758519a87d.png)
![屏幕截图 2023-03-14 194101](https://user-images.githubusercontent.com/119657362/224990579-07fbda27-ee67-4f03-8db1-8a3cbbf59cc5.png)

**Comment by mo-jinran** [comment]
点几下不起作用的选项，看看控制台是否有新的输出

**Comment by fishdown** [comment]
![屏幕截图 2023-03-14 194514](https://user-images.githubusercontent.com/119657362/224991187-50a4fcd5-4f5c-4790-96b5-20d3c22af157.png)

点的顺序是
主歌词字体自重
斜体
下划线
删除线

**Comment by mo-jinran** [comment]
第一个报错展开看一下

**Comment by fishdown** [comment]
![屏幕截图 2023-03-14 195319](https://user-images.githubusercontent.com/119657362/224993106-af6a4cf2-a2c6-42e8-8135-c553421f8d97.png)

**Comment by mo-jinran** [comment]
![image](https://user-images.githubusercontent.com/66980784/224993201-158dcfa6-ba85-4743-8ed1-7078fbc34948.png)
点右边蓝色的，发给我看看代码

**Comment by fishdown** [comment]
![屏幕截图 2023-03-14 195529](https://user-images.githubusercontent.com/119657362/224993426-e18711f9-f6e8-4234-bd18-b3bd6a17a04c.png)

**Comment by mo-jinran** [comment]
好怪无法复现，你先更新到1.5.1版本试试吧

**Comment by fishdown** [comment]
好的

**Comment by mo-jinran** [comment]
![image](https://user-images.githubusercontent.com/66980784/224995867-9b931bd1-5a33-4cc7-8cc0-42908d1d9712.png)
尝试删除后重启试试

**Comment by fishdown** [comment]
出现bug的时候 字重那是空白的，我点了下恢复默认，然后显示数值了，竟然可以了
![屏幕截图 2023-03-14 200618](https://user-images.githubusercontent.com/119657362/224996263-ff6e4887-d65e-4f77-9047-5310caeecfec.png)

**Comment by fishdown** [comment]
恢复正常了

**Comment by mo-jinran** [comment]
恢复默认的作用就是删除我上面发的那个选项（

**Comment by fishdown** [comment]
1.5.0 的时候我点过恢复默认，没起作用，我去文件夹，把之前的插件文件删了，重新下载了1.5.1   然后还是不正常，然后就顺手点了下恢复默认，就突然出现数值了，然后就正常了

**Comment by fishdown** [comment]
幸苦大佬
