### ISSUE TITLE
关闭网易云之后，taskbar-lyrics.exe进程不会自动退出，从而导致再次启动网易云时提示该进程无法访问

### ISSUE THREAD

**Issue by China-Mr-Hou** [mo-jinran/Taskbar-Lyrics#52]
关闭网易云之后，taskbar-lyrics.exe进程不会自动退出，从而导致再次启动网易云时提示该进程无法访问

**Comment by mo-jinran** [comment]
taskbar-lyrics.exe进程会自动关闭，只是重启速度太快导致在没结束前BetterNCM就尝试清空plugins_runtime导致这问题，目前没什么好的解决办法，只能下次更新把这个软件复制一份到其他目录运行了

**Comment by China-Mr-Hou** [comment]
好的，辛苦

**Comment by mo-jinran** [comment]
已修复，等待1.5.2版本更新
