### ISSUE TITLE
更新后一直显示等待插件传输歌词

### ISSUE THREAD

**Issue by JTFA** [mo-jinran/Taskbar-Lyrics#55]
并且设置里的下拉菜单似乎点击之后无反应

**Comment by chen310** [comment]
@mo-jinran  更新插件后，原来保存的设置中不存在 `retrieval_method` 导致报错，导致插件无法正常使用

**Comment by chen310** [comment]
@JTFA 可以先按 F12，删除插件数据
![cloudmusic_CaVJJubX4a](https://user-images.githubusercontent.com/33364396/225799761-f5083bf1-eada-46c9-a544-82ac77be4c45.png)

**Comment by mo-jinran** [comment]
> @mo-jinran 更新插件后，原来保存的设置中不存在 `retrieval_method` 导致报错，导致插件无法正常使用

已修复，保存的设置缺少键值时会使用默认的键值

**Comment by mo-jinran** [comment]
也可以点击标题旁边的恢复默认，跟清除Local Storage效果一致，区别是只会删除那一块单独的配置
