### ISSUE TITLE
插件故障反馈

### ISSUE THREAD

**Issue by 2055135** [mo-jinran/Taskbar-Lyrics#58]
更新后启动时Windows弹出警告，找不到文件
![image](https://user-images.githubusercontent.com/119772101/225817567-aa725498-50ff-4e55-aab3-d9b5d41efeaf.png)
Windows系统信息
版本	Windows 11 家庭中文版
版本	22H2
安装日期	‎2022/‎11/‎12
操作系统版本	22621.1413
体验	Windows Feature Experience Pack 1000.22639.1000.0

**Comment by 2055135** [comment]
且插件未启动

**Comment by SouLXH** [comment]
+1

**Comment by JTFA** [comment]
这个好像只有第一次启动会这样，关掉网易云重新打开就好了

**Comment by SouLXH** [comment]
> 这个好像只有第一次启动会这样，关掉网易云重新打开就好了

我这里并不是，升级了 再重装也不行 歌词不显示了

**Comment by Umbrakon** [comment]
+1

**Comment by SouLXH** [comment]
临时解决办法是去actions里面  下载最新的文件 放到提示缺失的地方 重启就好了。

**Comment by Umbrakon** [comment]
> 临时解决办法是去 actions 里面 下载最新的文件 放到提示缺失的地方 重启就好了。

有效！感谢！

**Comment by mo-jinran** [comment]
已尝试修复解决，等待更新
