### ISSUE TITLE
希望适配任务栏对齐方式"靠左"

### ISSUE THREAD

**Issue by little-creeper** [mo-jinran/Taskbar-Lyrics#6]
任务栏对其方式为"靠左"时歌词能居中显示

**Comment by mo-jinran** [comment]
优先实现此功能，或许还能顺便适配Windows 10

**Comment by mo-jinran** [comment]
![image](https://user-images.githubusercontent.com/66980784/213638529-d13651d2-025f-4fb5-89c5-f344430f15c5.png)
