### ISSUE TITLE
歌词位置显示

### ISSUE THREAD

**Issue by Meg-ZC** [mo-jinran/Taskbar-Lyrics#60]
![微信图片_20230318115219](https://user-images.githubusercontent.com/110646299/226083607-2cac66d1-921e-42f4-baf8-303f73d65671.png)
如图，显示一直都是左上角
系统版本：Windows 11 专业工作站版21H2

**Comment by mo-jinran** [comment]
重启解决，或者在窗口-切换屏幕中将父任务栏设置为主屏幕

**Comment by Meg-ZC** [comment]
![微信图片_20230318125159](https://user-images.githubusercontent.com/110646299/226087106-415042b4-d674-4aef-bfc7-03fcb33d96a7.png)
重启后仍未解决。没有连接其他显示器

**Comment by Meg-ZC** [comment]
系统从21h升级到22h后解决，done

**Comment by mo-jinran** [comment]
![image](https://user-images.githubusercontent.com/66980784/226619745-5ead94ab-1bdd-4b81-b596-803c8fcd3df3.png)
刚试了，无法复现，我这21H2是正常的（
