### ISSUE TITLE
歌词显示位置

### ISSUE THREAD

**Issue by China-Mr-Hou** [mo-jinran/Taskbar-Lyrics#62]
<img width="301" alt="image" src="https://user-images.githubusercontent.com/125100179/226114787-35c5cec5-4b49-43a8-8d9e-4ff86a38bb1e.png">
如图，两行歌词之间似乎增加了一行空白，导致第一行（主歌词）跑到了任务栏上边界以上而无法被看见
<img width="274" alt="image" src="https://user-images.githubusercontent.com/125100179/226114865-5d548a09-848c-40ac-9e57-db2ec8074c81.png">
设置为单行歌词独占也会错位

**Comment by China-Mr-Hou** [comment]
BetterNCM版本1.1.0    插件版本1.5.3
已经尝试过重启explorer.exe

**Comment by mo-jinran** [comment]
等待1.5.4版本，https://github.com/BetterNCM/BetterNCM-Plugins/pull/340

**Comment by mo-jinran** [comment]
应该能修好，一个小时前重写了文字排版
