### ISSUE TITLE
插件故障

### ISSUE THREAD

**Issue by 2055135** [mo-jinran/Taskbar-Lyrics#63]
插件已启用，但插件不工作，且无任何提示
![image](https://user-images.githubusercontent.com/119772101/226160047-a46a9cfd-6825-4862-8346-2a0a0ef4c963.png)
控制台信息
![image](https://user-images.githubusercontent.com/119772101/226160079-f74fddbf-75c6-4f62-9c1e-b6110b163d29.png)
当前Windows信息
版本	Windows 11 家庭中文版
版本	22H2
安装日期	‎2022/‎11/‎12
操作系统版本	22621.1413
体验	Windows Feature Experience Pack 1000.22639.1000.0

**Comment by mo-jinran** [comment]
请查看任务管理器中网易云音乐进程下是否存在taskbar-lyrics.exe，如果不存，则在网易云中点击打开插件文件夹，查看是否有taskbar-lyrics.exe程序，如果有，请双击打开运行是否能够显示

**Comment by 2055135** [comment]
任务管理器中网易云音乐进程下不存在taskbar-lyrics.exe，插件文件夹里存在taskbar-lyrics.exe程序，双击后能显示，但重启网易云后又不工作

**Comment by 2055135** [comment]
手动启动后插件似乎进入锁死状态，更改设置无效
复现视频，由于视频过大，使用百度网盘上传
链接: https://pan.baidu.com/s/1seBcQIGcPlEbS6S6UALuJg?pwd=95s9 提取码: 95s9

**Comment by mo-jinran** [comment]
> 手动启动后插件似乎进入锁死状态，更改设置无效 复现视频，由于视频过大，使用百度网盘上传 链接: https://pan.baidu.com/s/1seBcQIGcPlEbS6S6UALuJg?pwd=95s9 提取码: 95s9

因为需要给软件传递参数，你直接启动肯定不能用，他需要一个端口号跟插件端一致，是BetterNCM API端口+2

**Comment by mo-jinran** [comment]
任务栏歌词跟网易云音乐是互相独立的软件，没有任何联系，全靠本地服务器与插件进行网络通讯

**Comment by 0x00A0** [comment]
同样的问题,似乎版本更新后不会再自动启动taskbar-lyrics.exe了

**Comment by Caramel-Diode** [comment]
我想问一下为什么非要复制到到BetterNCM目录下再启动呢? 更新之前的这个bug是我自己修复的 发现可以直接在runtime里直接启动

**Comment by mo-jinran** [comment]
> 

https://github.com/mo-jinran/Taskbar-Lyrics/issues/52
https://github.com/mo-jinran/Taskbar-Lyrics/issues/48

**Comment by mo-jinran** [comment]
> 我想问一下为什么非要复制到到BetterNCM目录下再启动呢? 更新之前的这个bug是我自己修复的 发现可以直接在runtime里直接启动

https://github.com/mo-jinran/Taskbar-Lyrics/issues/48
https://github.com/mo-jinran/Taskbar-Lyrics/issues/52

**Comment by mo-jinran** [comment]
尝试更新1.5.5，看看能不能解决吧

**Comment by mo-jinran** [comment]
刚才抓了两位一样出问题的群友，现在已经修好了，等我发新版本

**Comment by 33333365548468** [comment]
> 

好滴加油奥

**Comment by mo-jinran** [comment]
已更新，刷新插件商店，将任务栏歌词更新至1.5.6版本

**Comment by 33333365548468** [comment]
> 

问题已解决，老哥牛逼
