### ISSUE TITLE
RuLyrics插件报错崩溃，啥都没动，昨天正常

### ISSUE THREAD

**Issue by dreamer521** [mo-jinran/Taskbar-Lyrics#66]
### 插件报错崩溃
`-------- BetterNCM CrashReport -------
BackTrace:
C:\betterncm\plugins_runtime\RuLyrics\RuLyrics.dll + 4397(7)
C:\betterncm\plugins_runtime\RuLyrics\RuLyrics.dll + 57AB8(cxxbridge1$rust_vec$str$reserve_total)
--------------------------------------
classname: "Shell_TrayWnd", traywin: 40100
-------- BetterNCM CrashReport -------
BackTrace:
C:\betterncm\plugins_runtime\RuLyrics\RuLyrics.dll + 1C32A(7)
C:\betterncm\plugins_runtime\RuLyrics\RuLyrics.dll + 1CB02(7)
C:\betterncm\plugins_runtime\RuLyrics\RuLyrics.dll + 1DDE5(BetterNCMPluginMain)
C:\Program Files (x86)\NetEase\CloudMusic\MSIMG32.dll + 6988D(TransparentBlt)
-------------------------------------`

**Comment by dreamer521** [comment]
![QQ截图20230322025429](https://user-images.githubusercontent.com/32254500/226714213-e12fe8d9-dd11-4385-ac04-ebe3fdbd5c81.png)

**Comment by mo-jinran** [comment]
建议删除“Rulyrics”插件，在betterncm的数据目录内的plugins目录下（数据目录默认为C:/betterncm）
然后打开网易云音乐，插件商店页面找到“任务栏歌词”插件并安装

**Comment by mo-jinran** [comment]
@MicroCBer
