### ISSUE TITLE
建议：建议纯音乐像无歌词音乐一样，任务栏歌词直接显示曲名和艺术家。

### ISSUE THREAD

**Issue by birdrocky** [mo-jinran/Taskbar-Lyrics#72]
目前网易云大部分纯音乐，会显示歌词“纯音乐，请欣赏。”，但是实际使用中用户会希望任务栏直接显示纯音乐的曲目名称和艺术家，不知是否可以实现，谢谢。
示例：
![1680338570521](https://user-images.githubusercontent.com/129585922/229275924-7567edc3-4578-4b84-94ba-044189fe8f23.jpg)

**Comment by mo-jinran** [comment]
![image](https://user-images.githubusercontent.com/66980784/229277005-fd2ec363-704f-400d-8ebd-45dc2927e772.png)

**Comment by mo-jinran** [comment]
等我更新下个版本
