### ISSUE TITLE
无法将歌词显示在任务栏右侧

### ISSUE THREAD

**Issue by CrissWu001** [mo-jinran/Taskbar-Lyrics#78]
以前是可以的，今天打开网易云发现歌词跑到左边了。现在选项里好像不能将歌词放在任务栏右边

**Comment by mo-jinran** [comment]
插件使用教学：
此处调整设置：
![image](https://user-images.githubusercontent.com/66980784/230910123-27a16afc-e7b3-414f-9f12-179b64e7956f.png)
