### ISSUE TITLE
歌词位置错误，无法左对齐

### ISSUE THREAD

**Issue by herexiong** [mo-jinran/Taskbar-Lyrics#8]
![image](https://user-images.githubusercontent.com/80973703/213668444-2aed3778-ec27-4e84-8456-d1472b680e05.png)

屏幕分辨率为2256*1504
windows版本为版本	Windows 11 专业版
版本	22H2
安装日期	‎2022/‎9/‎27
操作系统版本	22621.1105
体验	Windows Feature Experience Pack 1000.22638.1000.0

**Comment by mo-jinran** [comment]
更新到最新版本后这个问题是否有解决？
