### ISSUE TITLE
目前有两个BUG

### ISSUE THREAD

**Issue by Whuihuan** [mo-jinran/Taskbar-Lyrics#80]
1.在开小猫的情况下会有端口占用去访问gitee的情况，然后就会导致插件监听错误端口，无法传递歌词数据到任务栏。这个在不关闭小猫的情况下重载有几率解决，但是大部分都需要关闭小猫后重载或者打开前就关闭小猫
2.歌词来源选择RNP的时候，自动切曲显示的歌词还是上一曲的，除非手动切曲

**Comment by Whuihuan** [comment]
还有一个不知道是不是我要重装一下，我有些选项能下拉，但是点了没反应。有些下拉选项点完后下拉框不会收起

**Comment by mo-jinran** [comment]
下拉框没写点其他区域收起的逻辑

**Comment by mo-jinran** [comment]
问题一是已知的，我之前一直用的Clash For Windows 0.20.17版本没有这种问题，直到前几天我更新到0.20.20也可以复现了
下个版本会尝试解决

**Comment by mo-jinran** [comment]
> 下拉框没写点其他区域收起的逻辑

现在加上啦！不过还没传新版

**Comment by Whuihuan** [comment]
> > 下拉框没写点其他区域收起的逻辑
> 
> 现在加上啦！不过还没传新版

歌词使用RNP的时候因为自动切歌去window取歌词会因为RNP还没解析导致还是上一首的问题。这个比较影响使用（

**Comment by mo-jinran** [comment]
问题2也解决了，rnp给的歌词有给音乐id，循环判断是否一致即可
![image](https://user-images.githubusercontent.com/66980784/236142195-a2b7bbf4-0636-4fe0-8339-f7ca18fd98c0.png)

**Comment by mo-jinran** [comment]
问题1的话，暂时没什么比较优雅的解决办法（所以我将端口从BetterNCM的端口+2改成-2了（不过我试了几次是好的（（坏猫猫
