### ISSUE TITLE
调整不了字体大小

### ISSUE THREAD

**Issue by LiuXueYangNaya** [mo-jinran/Taskbar-Lyrics#82]
最新更新的1.6.2在设置里字体大小复选框里的点击无效
也就是说改不了大小（）
尝试了重启重载和重装插件还是木的办法
（更新前还是我自己的设置，更新之后字体大小就变了0.0）

**Comment by mo-jinran** [comment]
但是，我都没有做调节字体大小的选项

**Comment by LiuXueYangNaya** [comment]
对不起，我说的这个问题它好像对所有的复选框都一样
选择了之后并不能自行关闭，这就是问题qwq
还有，我说的字体大小是字重调整来着QAQ搞错了

发件人: ***@***.***>
发送时间: 2023年5月1日 18:48
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [mo-jinran/Taskbar-Lyrics] 调整不了字体大小 (Issue #82)


但是，我都没有做调节字体大小的选项

―

**Comment by mo-jinran** [comment]
诶呀，选择框没写点击其他地方收起的逻辑，还得再点一下选项收起（

**Comment by LiuXueYangNaya** [comment]
诶？
是这样子嘛

________________________________
发件人: 沫烬染 ***@***.***>
发送时间: 2023年5月3日 23:10
收件人: mo-jinran/Taskbar-Lyrics ***@***.***>
抄送: NayaCcR ***@***.***>; Author ***@***.***>
主题: Re: [mo-jinran/Taskbar-Lyrics] 调整不了字体大小 (Issue #82)


诶呀，选择框没写点击其他地方收起的逻辑，还得再点一下选项收起（

―

**Comment by mo-jinran** [comment]
好！下拉选择框咱修惹，可以点击其他地方收起啦
