### ISSUE TITLE
窗口位置左的设置，每次打开软件都要重新设置一遍

### ISSUE THREAD

**Issue by 18358639281** [mo-jinran/Taskbar-Lyrics#9]
窗口位置设置为左后，再次打开软件，还是会还原为右，挺麻烦的。
插件很好用，望优化。

**Comment by mo-jinran** [comment]
![image](https://user-images.githubusercontent.com/66980784/213960880-a7ad5db8-c8ca-4b9d-9314-f652b357d879.png)
是否开启过这个选项，没有用吗？

**Comment by 18358639281** [comment]
> 

没用欸。
开启后，重启网易云后，这个勾会自己去掉。

**Comment by 18358639281** [comment]
> ![image](https://user-images.githubusercontent.com/66980784/213960880-a7ad5db8-c8ca-4b9d-9314-f652b357d879.png) 是否开启过这个选项，没有用吗？

解决了，开启选项后要用BetterNCM重载插件。
